version: 0.0
os: linux
files:
  - source: /index.php
    destination: /var/www/html/
  - source: /config.php
    destination: /var/www/html/
  - source: /form-daftar.php
    destination: /var/www/html/
  - source: /form-edit.php
    destination: /var/www/html/
  - source: /hapus.php
    destination: /var/www/html/
  - source: /list-siswa.php
    destination: /var/www/html/
  - source: /proses-edit.php
    destination: /var/www/html/
  - source: /proses-pendaftaran.php
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

